use_frameworks!

target 'SHDropdownListView_Example' do
  pod 'SHDropdownListView', :path => '../'

  target 'SHDropdownListView_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
